num_control_points: 50
num_output_points: 100
point_density_beta: 1.25
noise_dimension: 10
gen_hid_node: 512
gen_hid_layer: 2
gen_hid_fun: LeakyRELU
alpha_range_step: [0,8,1]
Re_range_step: [1e5, 6e5, 1e5]
disc_conv_kernel: 7
disc_conv_channels: 16
cond_dim: 4
lr: 0.0001
epochs: 200
n_critic: 3
lambda_gp: 10
batch_size: 16
device: cuda  # 设置计算设备: auto (自动选择), cuda, 或 cpu